<h1>A Look Into COVID-19 Cases Between Ivy and Corresponding State Schools</h1>

In [21]:
import pandas as pd
colleges_df = pd.read_csv('../data/colleges.csv')

In [22]:
ivy_schools = ['Brown University', 'Columbia University', 'Cornell University', 'Dartmouth College', 'Harvard University', 'University of Pennsylvania', 'Princeton University', 'Yale University']
ivy_filter = colleges_df['college'].isin(ivy_schools) 
ivy_df = colleges_df[ivy_filter]
print(ivy_df)

            date          state         county           city  ipeds_id  \
205   2020-11-05    Connecticut      New Haven      New Haven  130794.0
655   2020-11-05  Massachusetts      Middlesex      Cambridge  166027.0
888   2020-11-05  New Hampshire        Grafton        Hanover  182670.0
916   2020-11-05     New Jersey         Mercer      Princeton  186131.0
973   2020-11-05       New York  New York City  New York City  190150.0
976   2020-11-05       New York       Tompkins         Ithaca  190415.0
1374  2020-11-05   Pennsylvania   Philadelphia   Philadelphia  215062.0
1396  2020-11-05   Rhode Island     Providence     Providence  217156.0

                         college  cases  \
205              Yale University  244.0
655           Harvard University  105.0
888            Dartmouth College   23.0
916         Princeton University   88.0
973          Columbia University   98.0
976           Cornell University  185.0
1374  University of Pennsylvania  660.0
1396            Brown University   43.0

                                                  notes
205   College reports only positive tests and may co...
655                                                 NaN
888                                                 NaN
916                                                 NaN
973                                                 NaN
976                                                 NaN
1374                                                NaN
1396                                                NaN

This is the data of just ivy league schools pulled out from the NYT dataset. From this data, we can see that the ivy with the most COVID-19 cases is UPenn. Not only does UPenn have the most cases, in comparison to the other ivy leagues that come in around 100 and 200, UPenn has an astounding 660 cases. For the sake of counting colleges by state, I am combining Cornell and Columbia, since they are both in New York. Their combined number of cases make 283, which makes New York ivies the second highest amount of cases.

In [16]:
SUNY = ['SUNY Albany',
        'SUNY Alfred State College of Technology',
        'SUNY Binghamton',
        'SUNY Brockport',
                  'SUNY Broome Community College',
                  'SUNY Buffalo State',
                  'SUNY Canton',
                  'SUNY Cobleskill',
                  'SUNY College at Potsdam',
                  'SUNY College of Environmental Science and Forestry',
                  'SUNY College of Optometry',
                  'SUNY Corning Community College',
                  'SUNY Cortland',
                  'SUNY Delhi',
                  'SUNY Downstate Health Sciences University',
                  'SUNY Empire State College',
                  'SUNY Geneseo',
                  'SUNY Maritime College',
                  'SUNY Morrisville',
                  'SUNY New Paltz',
                  'SUNY Old Westbury',
                  'SUNY Oneonta',
                  'SUNY Oswego',
                  'SUNY Plattsburgh',
                  'SUNY Polytechnic Institute',
                  'SUNY Purchase College',
                  'SUNY University at Buffalo',
                  'SUNY Westchester Community College',
                  'SUNY at Fredonia',]



umass = [          'University of Massachusetts Amherst', 
                  'University of Massachusetts Boston',
                  'University of Massachusetts Dartmouth'
                  'University of Massachusetts Lowell',
                  'University of Massachusetts Medical School',]

pennstate = ['Penn State University', 
                  'Penn State University Abington',
                  'Penn State University Altoona',
                  'Penn State University Beaver',
                  'Penn State University Behrend',
                  'Penn State University Berks',
                  'Penn State University Brandywine',
                  'Penn State University College of Medicine',
                  'Penn State University Dickinson Law',
                  'Penn State University DuBois',
                  'Penn State University Fayette',
                  'Penn State University Great Valley',
                  'Penn State University Greater Allegheny',
                  'Penn State University Harrisburg',
                  'Penn State University Hazleton',
                  'Penn State University Lehigh Valley',
                  'Penn State University Mont Alto',
                  'Penn State University New Kensington',
                  'Penn State University Schuylkill',
                  'Penn State University Scranton',
                  'Penn State University Shenango',
                  'Penn State University Wilkes-Barre',
                  'Penn State University York',]

uconn = ['Central Connecticut State University',
                  'Eastern Connecticut State University',
                  'Southern Connecticut State University',
                  'Western Connecticut State University']

state_colleges = ['University of Rhode Island', 
                  'Rutgers University', 'University of New Hampshire'] + SUNY + umass + uconn + pennstate

state__college_filter = colleges_df['college'].isin(state_colleges) 
state_colleges_df = colleges_df[state__college_filter]

In [17]:
college2group = { n: n.split(' ')[0] for n in SUNY }

college2group.update({ n : 'UCONN' for n in uconn})
college2group.update({ n : 'UMASS' for n in umass})
college2group.update({ n : 'PENNSTATE' for n in pennstate})

college2group['University of Rhode Island']='University of Rhode Island'
college2group['Rutgers University']='Rutgers University'
college2group['University of New Hampshire']='University of New Hampshire'

college2group

{'Central Connecticut State University': 'UCONN',
 'Eastern Connecticut State University': 'UCONN',
 'Penn State University': 'PENNSTATE',
 'Penn State University Abington': 'PENNSTATE',
 'Penn State University Altoona': 'PENNSTATE',
 'Penn State University Beaver': 'PENNSTATE',
 'Penn State University Behrend': 'PENNSTATE',
 'Penn State University Berks': 'PENNSTATE',
 'Penn State University Brandywine': 'PENNSTATE',
 'Penn State University College of Medicine': 'PENNSTATE',
 'Penn State University Dickinson Law': 'PENNSTATE',
 'Penn State University DuBois': 'PENNSTATE',
 'Penn State University Fayette': 'PENNSTATE',
 'Penn State University Great Valley': 'PENNSTATE',
 'Penn State University Greater Allegheny': 'PENNSTATE',
 'Penn State University Harrisburg': 'PENNSTATE',
 'Penn State University Hazleton': 'PENNSTATE',
 'Penn State University Lehigh Valley': 'PENNSTATE',
 'Penn State University Mont Alto': 'PENNSTATE',
 'Penn State University New Kensington': 'PENNSTATE',
 'Penn State University Schuylkill': 'PENNSTATE',
 'Penn State University Scranton': 'PENNSTATE',
 'Penn State University Shenango': 'PENNSTATE',
 'Penn State University Wilkes-Barre': 'PENNSTATE',
 'Penn State University York': 'PENNSTATE',
 'Rutgers University': 'Rutgers University',
 'SUNY Albany': 'SUNY',
 'SUNY Alfred State College of Technology': 'SUNY',
 'SUNY Binghamton': 'SUNY',
 'SUNY Brockport': 'SUNY',
 'SUNY Broome Community College': 'SUNY',
 'SUNY Buffalo State': 'SUNY',
 'SUNY Canton': 'SUNY',
 'SUNY Cobleskill': 'SUNY',
 'SUNY College at Potsdam': 'SUNY',
 'SUNY College of Environmental Science and Forestry': 'SUNY',
 'SUNY College of Optometry': 'SUNY',
 'SUNY Corning Community College': 'SUNY',
 'SUNY Cortland': 'SUNY',
 'SUNY Delhi': 'SUNY',
 'SUNY Downstate Health Sciences University': 'SUNY',
 'SUNY Empire State College': 'SUNY',
 'SUNY Geneseo': 'SUNY',
 'SUNY Maritime College': 'SUNY',
 'SUNY Morrisville': 'SUNY',
 'SUNY New Paltz': 'SUNY',
 'SUNY Old Westbury': 'SUNY',
 'SUNY Oneonta': 'SUNY',
 'SUNY Oswego': 'SUNY',
 'SUNY Plattsburgh': 'SUNY',
 'SUNY Polytechnic Institute': 'SUNY',
 'SUNY Purchase College': 'SUNY',
 'SUNY University at Buffalo': 'SUNY',
 'SUNY Westchester Community College': 'SUNY',
 'SUNY at Fredonia': 'SUNY',
 'Southern Connecticut State University': 'UCONN',
 'University of Massachusetts Amherst': 'UMASS',
 'University of Massachusetts Boston': 'UMASS',
 'University of Massachusetts DartmouthUniversity of Massachusetts Lowell': 'UMASS',
 'University of Massachusetts Medical School': 'UMASS',
 'University of New Hampshire': 'University of New Hampshire',
 'University of Rhode Island': 'University of Rhode Island',
 'Western Connecticut State University': 'UCONN'}

In [18]:
state_colleges_df['college_group']=state_colleges_df['college'].map(college2group).values
state_colleges_df

/usr/local/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

,date,state,county,city,ipeds_id,college,cases,notes,college_group
186,2020-11-05,Connecticut,Hartford,New Britain,128771.0,Central Connecticut State University,99.0,NaN,UCONN
188,2020-11-05,Connecticut,Windham,Windham,129215.0,Eastern Connecticut State University,52.0,NaN,UCONN
194,2020-11-05,Connecticut,New Haven,New Haven,130493.0,Southern Connecticut State University,59.0,NaN,UCONN
204,2020-11-05,Connecticut,Fairfield,Danbury,130776.0,Western Connecticut State University,30.0,NaN,UCONN
677,2020-11-05,Massachusetts,Hampshire,Amherst,166629.0,University of Massachusetts Amherst,180.0,NaN,UMASS
...,...,...,...,...,...,...,...,...,...
1355,2020-11-05,Pennsylvania,Lackawanna,Dunmore,214652.0,Penn State University Scranton,14.0,NaN,PENNSTATE
1356,2020-11-05,Pennsylvania,Mercer,Sharon,214634.0,Penn State University Shenango,0.0,NaN,PENNSTATE
1357,2020-11-05,Pennsylvania,Luzerne,Lehman,214643.0,Penn State University Wilkes-Barre,0.0,NaN,PENNSTATE
1358,2020-11-05,Pennsylvania,York,York,214829.0,Penn State University York,0.0,NaN,PENNSTATE
1404,2020-11-05,Rhode Island,Washington,Kingston,217484.0,University of Rhode Island,462.0,NaN,University of Rhode Island

In [19]:
state_colleges_df.groupby('college_group')['cases'].sum()

college_group
PENNSTATE                      4228.0
Rutgers University              396.0
SUNY                           3189.0
UCONN                           240.0
UMASS                           223.0
University of New Hampshire     275.0
University of Rhode Island      462.0
Name: cases, dtype: float64

For the sake of comparing colleges at the state level, I am condensing different campuses of state schools into one state school entity. For example, the different Penn State campuses will count towards one Penn State group. The state schools seem to trend how the ivies are, with Penn State having the most cases and SUNY having the second highest. However, unlike with the ivy league, SUNY seen to have a comparable amount of cases to Penn State, even though both Cornell and Columbia combined still totaled less than half of UPenn's cases.

In [20]:
state_colleges_df.groupby('college_group')['cases'].mean()

college_group
PENNSTATE                      183.826087
Rutgers University             396.000000
SUNY                           109.965517
UCONN                           60.000000
UMASS                           74.333333
University of New Hampshire    275.000000
University of Rhode Island     462.000000
Name: cases, dtype: float64

So these numbers are actually a bit misleading because with Rutgers and the U of RI, we can't calculate means since they only have one campus, whereas the other state schools have multiple campuses. Excluding those schools, this data supports our previous data. We see Penn State having the most average amount of cases, as well as SUNY coming in second here as well.